Cozastore/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cozastore.Controllers;

[Authorize(Roles = "Administrador, Funcionário")]
public class AdminController : Controller
{
    private readonly ILogger<AdminController> _logger;

    public AdminController(ILogger<AdminController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View("Error!");
    }
}

Cozastore/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cozastore.Data;
using Cozastore.Models;
using Microsoft.AspNetCore.Authorization;

namespace Cozastore.Controllers;

[Authorize(Roles = "Administrador, Funcionário")]
public class CategoriasController : Controller
{
    private readonly AppDbContext _context;
    private readonly IWebHostEnvironment _host;

    public CategoriasController(AppDbContext context, IWebHostEnvironment host)
    {
        _context = context;
        _host = host;
    }

    [HttpGet]
    public async Task<IActionResult> GetCategorias()
    {
        var categorias = await _context.Categorias
                .Include(c => c.CategoriaMae)
                .ToListAsync();
        return Json(new { data = categorias });
    }

    // GET: Categorias
    public async Task<IActionResult> Index()
    {
        var appDbContext = _context.Categorias.Include(c => c.CategoriaMae);
        return View(await appDbContext.ToListAsync());
    }

    // GET: Categorias/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var categoria = await _context.Categorias
            .Include(c => c.CategoriaMae)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (categoria == null)
        {
            return NotFound();
        }

        return View(categoria);
    }

    // GET: Categorias/Create
    public IActionResult Create()
    {
        ViewData["CategoriaMaeId"] = new SelectList(_context.Categorias, "Id", "Nome");
        return View();
    }

    // POST: Categorias/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Nome,Foto,Filtrar,Banner,CategoriaMaeId")] Categoria categoria, IFormFile Foto)
    {
        if (ModelState.IsValid)
        {
            _context.Add(categoria);
            await _context.SaveChangesAsync();
            if (Foto != null)
            {
                string fileName = categoria.Id + Path.GetExtension(Foto.FileName);
                string upload = Path.Combine(_host.WebRootPath, "img\\categorias");
                string newFile = Path.Combine(upload, fileName);
                using (var stream = new FileStream(newFile, FileMode.Create))
                {
                    Foto.CopyTo(stream);
                }
                categoria.Foto = "\\img\\categorias\\" + fileName;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["CategoriaMaeId"] = new SelectList(_context.Categorias, "Id", "Nome", categoria.CategoriaMaeId);
        return View(categoria);
    }

    // GET: Categorias/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var categoria = await _context.Categorias.FindAsync(id);
        if (categoria == null)
        {
            return NotFound();
        }
        ViewData["CategoriaMaeId"] = new SelectList(_context.Categorias, "Id", "Nome", categoria.CategoriaMaeId);
        return View(categoria);
    }

    // POST: Categorias/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Foto,Filtrar,Banner,CategoriaMaeId")] Categoria categoria, IFormFile NovaFoto)
    {
        if (id != categoria.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                if (NovaFoto != null)
                {
                    string fileName = categoria.Id + Path.GetExtension(NovaFoto.FileName);
                    string upload = Path.Combine(_host.WebRootPath, "img\\categorias");
                    string newFile = Path.Combine(upload, fileName);
                    using (var stream = new FileStream(newFile, FileMode.Create))
                    {
                        NovaFoto.CopyTo(stream);
                    }
                    categoria.Foto = "\\img\\categorias\\" + fileName;
                    await _context.SaveChangesAsync();
                }
                _context.Update(categoria);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoriaExists(categoria.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["CategoriaMaeId"] = new SelectList(_context.Categorias, "Id", "Nome", categoria.CategoriaMaeId);
        return View(categoria);
    }

    // GET: Categorias/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var categoria = await _context.Categorias
            .Include(c => c.CategoriaMae)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (categoria == null)
        {
            return NotFound();
        }

        return View(categoria);
    }

    // POST: Categorias/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var categoria = await _context.Categorias.FindAsync(id);
        if (categoria != null)
        {
            _context.Categorias.Remove(categoria);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool CategoriaExists(int id)
    {
        return _context.Categorias.Any(e => e.Id == id);
    }
}

Cozastore/Controllers/CoresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Cozastore.Data;
using Cozastore.Models;
using Microsoft.AspNetCore.Authorization;

namespace Cozastore.Controllers;

[Authorize(Roles = "Administrador, Funcionário")]
public class CoresController : Controller
{
    private readonly AppDbContext _context;

    public CoresController(AppDbContext context)
    {
        _context = context;
    }

    // GET: Cores
    public async Task<IActionResult> Index()
    {
        return View(await _context.Cores.ToListAsync());
    }

    // GET: Cores/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cor = await _context.Cores
            .FirstOrDefaultAsync(m => m.Id == id);
        if (cor == null)
        {
            return NotFound();
        }

        return View(cor);
    }

    // GET: Cores/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Cores/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Nome,CodigoHexa")] Cor cor)
    {
        if (ModelState.IsValid)
        {
            if (!CorExists(cor))
            {
                _context.Add(cor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError(string.Empty, "Nome já cadastrado");
        }
        return View(cor);
    }

    // GET: Cores/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cor = await _context.Cores.FindAsync(id);
        if (cor == null)
        {
            return NotFound();
        }
        return View(cor);
    }

    // POST: Cores/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,CodigoHexa")] Cor cor)
    {
        if (id != cor.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(cor);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CorExists(cor))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(cor);
    }

    // GET: Cores/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cor = await _context.Cores
            .FirstOrDefaultAsync(m => m.Id == id);
        if (cor == null)
        {
            return NotFound();
        }

        return View(cor);
    }

    // POST: Cores/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var cor = await _context.Cores.FindAsync(id);
        if (cor != null)
        {
            _context.Cores.Remove(cor);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool CorExists(Cor cor)
    {
        if (cor.Id == 0)
            return _context.Cores.Any(e => e.Nome == cor.Nome);
        else
            return _context.Cores.Any(e => e.Id == cor.Id);
    }
}

Cozastore/Controllers/TamanhosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Cozastore.Data;
using Cozastore.Models;

namespace Cozastore.Controllers;

public class TamanhosController : Controller
{
    private readonly AppDbContext _context;

    public TamanhosController(AppDbContext context)
    {
        _context = context;
    }

    // GET: Tamanhos
    public async Task<IActionResult> Index()
    {
        return View(await _context.Tamanhos.ToListAsync());
    }

    // GET: Tamanhos/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var tamanho = await _context.Tamanhos
            .FirstOrDefaultAsync(m => m.Id == id);
        if (tamanho == null)
        {
            return NotFound();
        }

        return View(tamanho);
    }

    // GET: Tamanhos/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Tamanhos/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Sigla,Nome")] Tamanho tamanho)
    {
        if (ModelState.IsValid)
        {
            _context.Add(tamanho);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(tamanho);
    }

    // GET: Tamanhos/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var tamanho = await _context.Tamanhos.FindAsync(id);
        if (tamanho == null)
        {
            return NotFound();
        }
        return View(tamanho);
    }

    // POST: Tamanhos/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Sigla,Nome")] Tamanho tamanho)
    {
        if (id != tamanho.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(tamanho);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TamanhoExists(tamanho.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(tamanho);
    }

    // GET: Tamanhos/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var tamanho = await _context.Tamanhos
            .FirstOrDefaultAsync(m => m.Id == id);
        if (tamanho == null)
        {
            return NotFound();
        }

        return View(tamanho);
    }

    // POST: Tamanhos/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var tamanho = await _context.Tamanhos.FindAsync(id);
        if (tamanho != null)
        {
            _context.Tamanhos.Remove(tamanho);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool TamanhoExists(int id)
    {
        return _context.Tamanhos.Any(e => e.Id == id);
    }
}

Cozastore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cozastore - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cozastore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cozastore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cores" asp-action="Index">Cores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Tamanhos" asp-action="Index">Tamanho</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">Categoria</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Cozastore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Cozastore/Views/Shared/_LayoutAdmin.cshtml
<!--
=========================================================
* Material Dashboard 2 - v3.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2023 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="pt-br" style="min-height: 100vh;">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="~/img/icons/favicon.png">
  <title>
    CozaStore - Área Administrativa
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="~/assets/css/material-dashboard.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css" />
  @await RenderSectionAsync("Styles", required: false)

</head>

<body class="g-sidenav-show  bg-gray-200" style="min-height: 100vh;">
  <aside
    class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark"
    id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
        aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand text-center" asp-controller="Admin" asp-action="Index">
        <img src="~/img/icons/logo-02.png" class="navbar-brand-img" alt="main_logo">
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class='nav-link text-white @(ViewData["Title"].ToString() == "Dashboard" ? "active bg-gradient-warning" : "")'
            asp-controller="Admin" asp-action="Index">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Cadastros</h6>
        </li>
        <li class="nav-item">
          <a class='nav-link text-white @(ViewData["Title"].ToString() == "Produtos" ? "active bg-gradient-warning" : "")'
            asp-controller="Produtos" asp-action="Index">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">inventory_2</i>
            </div>
            <span class="nav-link-text ms-1">Produtos</span>
          </a>
        </li>
        <li class="nav-item">
          <a class='nav-link text-white @(ViewData["Title"].ToString() == "Categorias" ? "active bg-gradient-warning" : "")'
            asp-controller="Categorias" asp-action="Index">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">category</i>
            </div>
            <span class="nav-link-text ms-1">Categorias</span>
          </a>
        </li>
        <li class="nav-item">
          <a class='nav-link text-white @(ViewData["Title"].ToString() == "Cores" ? "active bg-gradient-warning" : "")'
            asp-controller="Cores" asp-action="Index">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">palette</i>
            </div>
            <span class="nav-link-text ms-1">Cores</span>
          </a>
        </li>
        <li class="nav-item">
          <a class='nav-link text-white @(ViewData["Title"].ToString() == "Tamanhos" ? "active bg-gradient-warning" : "")'
            asp-controller="Tamanhos" asp-action="Index">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">format_size</i>
            </div>
            <span class="nav-link-text ms-1">Tamanhos</span>
          </a>
        </li>
        <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Segurança</h6>
        </li>
        <li class="nav-item">
          <a class='nav-link text-white @(ViewData["Title"].ToString() == "Usuários" ? "active bg-gradient-warning" : "")'
            asp-controller="Usuarios" asp-action="Index">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">account_circle</i>
            </div>
            <span class="nav-link-text ms-1">Usuários</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
      <form asp-action="Logout" asp-controller="Account" method="POST" class="mx-3">
        <button type="submit" class="btn bg-gradient-danger w-100">
          <i class="material-icons opacity-10">logout</i>
          Sair
        </button>
      </form>
    </div>
  </aside>
  <main class="main-content border-radius-lg d-flex flex-column" style="min-height: 100vh;">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
      data-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">
                Página
              </a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">@ViewData["Title"]</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">@ViewData["Title"]</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
            <partial name="_LayoutAdminLogin.cshtml">
          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid pt-3 pe-3 flex-grow-1">

      @RenderBody()

    </div>
    <footer class="footer pb-3 w-100">
      <div class="container-fluid">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col mb-lg-0 mb-4">
            <div class="copyright text-center text-sm text-muted">
              ©
              @DateTime.Now.Year,
              desenvolvido por <a href="https://gallojunior.github.io" class="font-weight-bold" target="_blank">
                José Antonio Gallo Junior
              </a>
              com template de
              <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>.
            </div>
          </div>
        </div>
      </div>
    </footer>
  </main>

  <!--   Core JS Files   -->
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/assets/js/core/popper.min.js"></script>
  <script src="~/assets/js/core/bootstrap.min.js"></script>
  <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="~/assets/js/material-dashboard.js"></script>
  <script src="~/assets/js/site.js"></script>
  <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
  <partial name="_ValidationScriptsPartial.cshtml"></partial>

  <partial name="_SuccessNotification"></partial>
  <partial name="_WarningNotification"></partial>

  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Cozastore/Views/Shared/_LayoutAdminLogin.cshtml
@using System.Security.Claims
@inject Cozastore.Data.AppDbContext _context;
@{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var user = _context.Usuarios.Find(userId);
    var foto = user != null ? user.Foto ?? Url.Content("~/img/usuarios/no-photo.jpg") : Url.Content("~/img/usuarios/no-photo.jpg");
}

<li class="nav-item d-flex align-items-center">
    <a asp-controller="Admin" asp-action="Profile" class="nav-link text-body font-weight-bold px-0">
        <img class="img-fluid rounded-circle mx-1 mb-1" src="@foto" width="32" height="28">
        <span class="d-sm-inline d-none">@(user != null ? user.Nome : "Usuário")</span>
    </a>
</li>

Cozastore/Views/Shared/_SuccessNotification.cshtml
<div class="toast-container position-absolute pt-6 pe-3 top-0 end-0" id="toastPlacement">
  <div class="toast fade hide p-2 bg-white shadown-success" role="alert" aria-live="assertive" id="successToast"
    aria-atomic="true">
    <div class="toast-header bg-gradient-success border-0 rounded">
      <i class="material-icons text-white me-2">
        check
      </i>
      <span class="me-auto font-weight-bold text-white">CozaStore </span>
      <i class="fas fa-times text-md ms-3 cursor-pointer text-white" data-bs-dismiss="toast" aria-label="Close"></i>
    </div>
    <hr class="horizontal light m-0">
    <div class="toast-body">
      <span class="font-weight-bold text-dark">@TempData["Success"]</span>
    </div>
  </div>
</div>

@if (TempData["Success"] != null)
{
  <script>
    var myToastEl = document.getElementById('successToast');
    var myToast = bootstrap.Toast.getOrCreateInstance(myToastEl);
    myToast.show();
  </script>
}

Cozastore/Views/Shared/_WarningNotification.cshtml
<div class="toast-container position-absolute pt-6 pe-3 top-0 end-0" id="toastPlacement">
  <div class="toast fade hide p-2 bg-white shadow-warning" role="alert" aria-live="assertive" id="warningToast"
    aria-atomic="true">
    <div class="toast-header bg-gradient-warning border-0 rounded">
      <i class="material-icons text-white me-2">
        warning
      </i>
      <span class="me-auto font-weight-bold text-white">CozaStore </span>
      <i class="fas fa-times text-md ms-3 cursor-pointer text-white" data-bs-dismiss="toast" aria-label="Close"></i>
    </div>
    <hr class="horizontal light m-0">
    <div class="toast-body">
      <span class="font-weight-bold text-dark">
        <div asp-validation-summary="ModelOnly"></div>
      </span>
    </div>
  </div>
</div>

@if (ViewData.ModelState.Where(e => e.Key == string.Empty).Count() > 0)
{
  <script>
    var myToastEl = document.getElementById('warningToast');
    var myToast = bootstrap.Toast.getOrCreateInstance(myToastEl);
    myToast.show();
  </script>
}